AllCops:
  TargetRubyVersion: 2.7
  NewCops: disable
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Security/Eval:
  Enabled: false

Style/LambdaCall:
  Enabled:
    EnforcedStyle: braces

Style/RedundantSelf:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled:
    EnforcedStyle: indented

Layout/LineLength:
  Enabled:
    max: 100

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/AbcSize:
  Exclude:
    - lib/lazy_names.rb
